name: Deploy Frontend (RealEstate FE)

on:
  push:
    branches:
      - pre
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: [self-hosted, pre-realestate-fe]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create frontend env file
        run: |
          cat <<EOF > .env
          VITE_API_URL=${{ secrets.PRE_VITE_API_URL }}
          VITE_APP_ENV=production
          VITE_APP_NAME=${{ secrets.PRE_VITE_APP_NAME }}
          VITE_BACKEND_URL=https://preapi.realinvesto.com
          EOF

      - name: Build & Deploy Frontend
        run: |
          docker compose up -d --build

      - name: Cleanup unused images
        run: |
          docker image prune -f
